# Site settings
author: Pardeep Kaur
title: Software Development 
header-img: img/home-bg.png
email: pkaur84@aol.com
copyright_name: Pardeep Kaur
description: > # this means to ignore newlines until "baseurl:"
  'Why did i decide to learn software development'.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  pardeep942

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
